#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tle-meur <tle-meur@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/17 10:09:46 by tle-meur          #+#    #+#              #
#    Updated: 2015/09/17 10:09:48 by tle-meur         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) main.c

clean:
	rm -f $(NAME)

fclean: clean

re: clean all
